### ISSUE TITLE
Business Central war fails to deploy

### ISSUE THREAD

**Issue by eschabell** [redhatdemocentral/rhcs-coolstore-persistence-demo#5]
On container EAP start, right at end:

09:55:37,971 INFO [org.jboss.as.server.deployment.scanner] (DeploymentScanner-threads - 1) WFLYDS0004: Found business-central.war in deployment directory. To trigger deployment create a file called business-central.war.dodeploy

Since when do we need a 'dodeploy'?

**Comment by sthakor1** [comment]
I am seeing this issue as well.  Any updates on how this can be fixed?

**Comment by eschabell** [comment]
I am seeing this in the log: 

09:24:49,756 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("deploy") failed - address: ([("deployment" => "business-central.war")]) - failure description: {"WFLYCTL0180: Services with missing/unavailable dependencies" => [
    "jboss.persistenceunit.\"business-central.war#org.jbpm.domain\".__FIRST_PHASE__ is missing [jboss.naming.context.java.jboss.datasources.PostgresDS]",
    "jboss.persistenceunit.\"business-central.war#org.jbpm.domain\" is missing [jboss.naming.context.java.jboss.datasources.PostgresDS]"
]}


I Need to fix the persistence configuration. Stand by.
